#!/usr/bin/env bash
# Build the agent-box cloud-init template on a Proxmox VE host.
#
# Usage: ./build-template.sh [--force]
#   --force : destroy and rebuild if the template already exists
#
# Run this on the PVE host (or anywhere with qm/pvesm/wget). Source of truth
# for IDs/storage/bridge is config.sh next to this script.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

FORCE=0
for arg in "$@"; do
  case "$arg" in
  --force) FORCE=1 ;;
  *)
    echo "Unknown argument: $arg" >&2
    exit 1
    ;;
  esac
done

# config.sh is generated by the user from config.example.sh, so it can't be
# statically followed by shellcheck.
# shellcheck source=/dev/null disable=SC1091
source "$REPO_ROOT/config.sh"

log() { printf '\033[1;34m[template]\033[0m %s\n' "$*"; }
fail() {
  printf '\033[1;31m[template] ERROR:\033[0m %s\n' "$*" >&2
  exit 1
}

require() { command -v "$1" >/dev/null 2>&1 || fail "missing required command: $1"; }

for cmd in qm pvesm wget; do require "$cmd"; done

pvesm status | grep -q "^${STORAGE}\b" || fail "storage '${STORAGE}' not found"
if [[ -n "$SNIPPET_STORAGE" ]]; then
  pvesm status | grep -q "^${SNIPPET_STORAGE}\b" ||
    fail "snippet storage '${SNIPPET_STORAGE}' not found (does it accept snippet content?)"
fi

TEMPLATE_NAME="agent-box-tmpl-noble"

if qm status "$TEMPLATE_ID" >/dev/null 2>&1; then
  IS_TEMPLATE="$(qm config "$TEMPLATE_ID" | grep -c '^template: 1$' || true)"
  if ((FORCE)); then
    log "--force given, destroying existing VM/template ${TEMPLATE_ID}"
    qm stop "$TEMPLATE_ID" >/dev/null 2>&1 || true
    qm destroy "$TEMPLATE_ID" --purge --destroy-unreferenced-disks 1
  elif ((IS_TEMPLATE)); then
    log "template ${TEMPLATE_ID} (${TEMPLATE_NAME}) already exists — nothing to do."
    log "Use --force to rebuild, or just run create-vm.sh to clone it."
    exit 0
  else
    fail "VM ID ${TEMPLATE_ID} exists but is NOT a template; pick another TEMPLATE_ID or delete it"
  fi
fi

IMG="/tmp/${TEMPLATE_NAME}.img"
log "ensuring Ubuntu cloud image is present at ${IMG}"
wget -q --show-progress -O "${IMG}.part" "$CLOUD_IMAGE_URL"
mv "${IMG}.part" "$IMG"

log "creating VM ${TEMPLATE_ID} (${TEMPLATE_NAME})"
qm create "$TEMPLATE_ID" \
  --name "$TEMPLATE_NAME" \
  --memory 2048 --balloon 0 \
  --cores 2 \
  --net0 virtio,bridge="$BRIDGE"${NET_VLAN_TAG:+,tag=$NET_VLAN_TAG} \
  --scsihw virtio-scsi-pci \
  --ostype l26 \
  --serial0 socket --vga serial0 \
  --agent enabled=1,fstrim_cloned_disks=1 \
  --boot order=scsi0

log "importing disk image into storage '${STORAGE}'"
IMPORT_OUT="$(qm importdisk "$TEMPLATE_ID" "$IMG" "$STORAGE" --format raw 2>&1)"
rm -f "$IMG"

DISK_REF="$(printf '%s\n' "$IMPORT_OUT" | sed -n 's/^unused0:[^:]*:\(.*\)$/\1/p' | tail -n1 | tr -d '[:space:]')"
DISK_REF="${DISK_REF%.1}" # importdisk may append a transfer-progress suffix like ".100%"
if [[ -z "$DISK_REF" ]]; then
  DISK_REF="vm-${TEMPLATE_ID}-disk-0"
  log "could not parse importdisk output, assuming disk '${DISK_REF}'"
fi

qm set "$TEMPLATE_ID" --scsi0 "${STORAGE}:${DISK_REF},discard=on,ssd=1"

log "attaching cloud-init drive and serial console bits"
qm set "$TEMPLATE_ID" --ide2 "${SNIPPET_STORAGE}:cloudinit" --boot order=scsi0
qm set "$TEMPLATE_ID" --ciuser "$ADMIN_USER"

log "converting to template"
qm template "$TEMPLATE_ID"

log "done. Template ${TEMPLATE_ID} (${TEMPLATE_NAME}) is ready."
echo
echo "Next step: create dev boxes with:"
echo "  $SCRIPT_DIR/create-vm.sh [-n name] [-i vmid]"
